wwt/SwiftCurrent

.github/workflows/release.yml, README.md
=> [status-badge] - Status badge now points to actual Workflow CI - TT HM

.github/workflows/trunk.yml, fastlane/Fastfile
…which was already deleted in another PR - RAG
----
----
=> Removing need for the Info.plist for versioning

wiki/Getting-Started-UIKit.md, wiki/Getting-Started.md, wiki/Installation.md
=> Enhances clarity and accuracy of Installation guide

.github/workflows/trunk.yml, README.md
=> Fixes doc generation and adds SPM badge

.github/workflows/trunk.yml
=> Updates pipeline to use Release Token

.clabot
Removed .clabot to remove CLA-bot and only rely on SAP's cla-assistant - TT RAG
----
----
=> Changes CLA servicer

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
=> Updates Contributing.md with CLA information

.github/.codecov.yml
=> Exclude tests from coverage

ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/ModalStyleTests.swift, ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/TestUtilities/TopViewController.swift, ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/UIKitConsumerPersistenceTests.swift, SwiftCurrent.xcworkspace/xcshareddata/xcschemes/SwiftCurrent_UIKit.xcscheme, Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUITests.swift
=> Adds debugging to help diagnose flakey test

README.md, wiki/Getting-Started-Storyboard.md, wiki/Getting-Started-SwiftUI.md, wiki/Getting-Started-UIKit.md
=> Updates links in README.md to show updated content

Sources/SwiftCurrent_SwiftUI/Views/ModifiedWorkflowView.swift, Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUITests.swift, wiki/Getting-Started-SwiftUI.md
=> Fixes relaunching WorkflowViews

.github/build-xcframework.sh, .github/workflows/trunk.yml, build-xcframework.sh
=> Adds xcframework files to our git releases

ExampleApps/SwiftUIExample/SwiftUIExample.xcodeproj/project.pbxproj, ExampleApps/SwiftUIExample/SwiftUIExample/UIKitInterop/UIKitInteropProgrammaticViewController.swift, ExampleApps/SwiftUIExample/SwiftUIExampleTests/UIKitInterop.storyboard, ExampleApps/SwiftUIExample/SwiftUIExampleTests/UIKitInteropTests.swift, ExampleApps/SwiftUIExample/SwiftUIExampleTests/ViewInspector/InspectableExtensions.swift, ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/ContentViewTests.swift, ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/SwiftUIInteropTests.swift, ExampleApps/UIKitExample/UIKitExample.xcodeproj/project.pbxproj, Sources/SwiftCurrent_SwiftUI/UIKitInterop/HostedWorkflowItem.swift, Sources/SwiftCurrent_SwiftUI/Views/ViewControllerWrapper.swift, Sources/SwiftCurrent_SwiftUI/WorkflowItem.swift, wiki/Getting-Started-SwiftUI.md, wiki/Getting-Started-UIKit.md
=> Adds interoperability between UIKit and SwiftUI to SwiftCurrent

ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/TestConstant.swift, ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/UIKitConsumerTests.swift, ExampleApps/UIKitExample/UIKitExample.xcodeproj/project.pbxproj, Sources/SwiftCurrent_UIKit/Extensions/UIViewControllerAdditions.swift
=> Adds ability to launchInto an `AnyWorkflow`

README.md
=> Adds special thanks section to README that recognizes test dependencies

.github/fastlane/Fastfile, .github/workflows/CI.yml, .github/workflows/PR_CI.yml
=> General pipeline optimization

.github/abstract/Creating Workflows in SwiftUI.md
Proofread and made minimal changes.
----
----
=> Proofread and Made Minimal Changes to Creating Workflows in SwiftUI

.github/abstract/Creating Workflows in UIKit.md
Proofread and made minor changes.
----
----
=> Proofread and Made Minor Changes to Creating Workflows in UIKit

.github/abstract/Controlling Presentation.md
=> Proofread and made minimal changes to Controlling Presentation.

.github/guides/Installation.md
Proofread and made updates.
----
----
=> Proofread and Made Updates to Installation

.github/guides/Working with NavigationView.md
Proofread and updated.
----
----
=> Proofread and Updated Working with NavigationView

.github/guides/Using Storyboards.md
Proofread and updated.
----
----
=> Updated Using Storyboards Guide

.github/guides/Why This Library.md
=> Updated Why This Library Section

.github/guides/Using Programmatic Views.md
Proofread and made changes.
----
----
=> Made changes to Using Programmatic Views Guide.

.github/.codecov.yml
…hen running the UI tests - RAG
----
----
=> Adds TestViews to code coverage exclusion

.github/workflows/CI.yml, .github/workflows/PR_CI.yml, .github/workflows/release.yml, .github/workflows/trunk.yml, ExampleApps/SwiftUIExample/SwiftUIExample/ViewInspector/InspectableAlert.swift, ExampleApps/SwiftUIExample/SwiftUIExample/ViewInspector/InspectableSheet.swift, ExampleApps/SwiftUIExample/SwiftUIExampleTests/ViewInspector/InspectableExtensions.swift, Package.swift, Sources/SwiftCurrent_SwiftUI/ViewInspector/InspectableSheet.swift, SwiftCurrent.xcworkspace/xcshareddata/swiftpm/Package.resolved, Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_ModalTests.swift, Tests/SwiftCurrent_SwiftUITests/ViewInspector/InspectableExtensions.swift
=> Updated Develop Dependencies

.github/workflows/validate_urls.yml
=> Url checking upgrades

.github/workflows/validate_urls.yml
=> Slack message fix

.github/SwiftCurrentLint/.swiftlint.yml
=> Fixed copyright linting

.github/STYLEGUIDE.md
=> Moves class attributes onto new lines.

Sources/SwiftCurrent_SwiftUI/Extensions/WorkflowDecodableExtensions.swift, Sources/SwiftCurrent_SwiftUI/Models/ExtendedFlowRepresentableMetadata.swift, Sources/SwiftCurrent_SwiftUI/Views/WorkflowItem.swift, Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUITests.swift, Tests/SwiftCurrent_SwiftUITests/WorkflowDecodableExtensionsTests.swift
Co-authored-by: Matt Freiburg <Matt.Freiburg@wwt.com>
=> Adds flow persistence decoding

ExampleApps/SwiftUIExample/SwiftUIExample.xcodeproj/project.pbxproj, ExampleApps/SwiftUIExample/SwiftUIExample/TestViews/TestView.swift, Sources/SwiftCurrent_SwiftUI/Views/ViewControllerWrapper.swift
=> [fix-212] - Add UIKit views to play with in sample app and fix #212 - TT

ExampleApps/SwiftUIExample/SwiftUIExampleTests/UIKitInteropTests.swift
=> Build crash fix

.github/workflows/CI.yml, .github/workflows/PR_CI.yml
#206 
- https://github.com/marketplace/actions/codecov#arguments
I'm not sure how to test this will actually fix the issue, but it does change the problem from not finding any coverage to finding at least 1 correct report.
=> Fix codecov report
