wwt/SwiftCurrent

- .github/PULL_REQUEST_TEMPLATE.md
- changelog_configuration.json
> [changelog-configuration] - Add in changelog config - TT HM

- README.md
- wiki/Getting-Started-UIKit.md
- wiki/Home.md
> Creates Getting Started with Programmatic UIKit

- .github/PULL_REQUEST_TEMPLATE.md
> Update PR Template to direct contributors to remove unneeded checklist items

- ExampleApps/UIKitExample/README.md
- ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/Storyboard/StoryboardLoadableTests.swift
- ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/Storyboard/TestStoryboard.storyboard
- ExampleApps/UIKitExample/UIKitExample.xcodeproj/project.pbxproj
- ExampleApps/UIKitExample/UIKitExample/Base.lproj/Main.storyboard
- ExampleApps/UIKitExample/UIKitExample/Ordering/TermsOfServiceViewController.swift
- ExampleApps/UIKitExample/UIKitExample/SetupViewController.swift
- ExampleApps/UIKitExample/UIKitExample/TermsOfServiceViewController.swift
- ExampleApps/UIKitExample/UIKitExampleTests/TermsOfServiceViewControllerTests.swift
- Sources/SwiftCurrent/Protocols/FlowRepresentable.swift
- Sources/SwiftCurrent/TypeErased/AnyFlowRepresentable.swift
- Sources/SwiftCurrent_UIKit/StoryboardLoadable.swift
- Tests/SwiftCurrentTests/PassthroughFlowRepresentableTests.swift
- Tests/UIKitExampleTests/SetupViewControllerTests.swift
- Tests/UIKitExampleTests/TestFinder.swift
> Fixes StoryboardLoadable protocol not working with AnyWorkflow.PassedArgs

- Sources/SwiftCurrent_SwiftUI/Models/WorkflowViewModel.swift
- Sources/SwiftCurrent_SwiftUI/Views/ModifiedWorkflowView.swift
- Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUITests.swift
- Tests/SwiftCurrent_SwiftUITests/WorkflowViewModelTests.swift
> Fixes relaunching issue in SwiftUI when isLaunched is a constant of true

- .github/CONTRIBUTING.md
> Adding section regarding commit message format to CONTRIBUTING.md.

- .github/workflows/CI.yml
> Sets CI to only run on pushes to main branch

- .github/SwiftCurrentLint/.swiftlint.yml
- .github/guides/Working with Modals.md
- ExampleApps/SwiftUIExample/SwiftCurrent_SwiftUI_UITests/Info.plist
- ExampleApps/SwiftUIExample/SwiftCurrent_SwiftUI_UITests/SwiftCurrent_SwiftUI_UITests.swift
- ExampleApps/SwiftUIExample/SwiftUIExample.xcodeproj/project.pbxproj
- ExampleApps/SwiftUIExample/SwiftUIExample.xcodeproj/xcshareddata/xcschemes/SwiftUIExample.xcscheme
- ExampleApps/SwiftUIExample/SwiftUIExample/SwiftUIExampleApp.swift
- ExampleApps/SwiftUIExample/SwiftUIExample/TestViews/TestEnumerations.swift
- ExampleApps/SwiftUIExample/SwiftUIExample/TestViews/TestView.swift
- Sources/SwiftCurrent_SwiftUI/Extensions/SwiftUILaunchStyleAdditions.swift
- Sources/SwiftCurrent_SwiftUI/Protocols/WorkflowItemPresentable.swift
- Sources/SwiftCurrent_SwiftUI/Views/WorkflowItem.swift
- SwiftCurrent.xcworkspace/xcshareddata/xcschemes/SwiftCurrent.xcscheme
- Tests/SwiftCurrent_SwiftUITests/GenericConstraintTests.swift
- Tests/SwiftCurrent_SwiftUITests/SwiftUILaunchStyleAdditionTests.swift
> Adds support for Full screen cover modal presentation style

- .github/guides/Working with Modals.md
Proofread and made changes.
----
----
> Update Working with Modals.md

- Sources/SwiftCurrent/Models/Workflow.swift
- Sources/SwiftCurrent/Protocols/FlowRepresentable.swift
- Sources/SwiftCurrent_UIKit/Extensions/UIViewControllerAdditions.swift
> Updates API documentation based on technical writing suggestions.

- .github/workflows/trunk.yml
Because https://github.com/actions/virtual-environments/issues/4320 has merged and deployed, we should no longer need to gem install jazzy before generating documents.  This should decrease our document deployment time by ~4 minutes.
> Removes jazzy from install steps when deploying new versions

- Sources/SwiftCurrent_SwiftUI/Views/WorkflowLauncher.swift
- Tests/SwiftCurrent_SwiftUITests/GenericConstraintTests.swift
> Fixes WorkflowLauncher to accept arguments when first FR has input of Never

- Sources/SwiftCurrent_SwiftUI/Extensions/ThenProceedExtensions.swift
- Tests/SwiftCurrent_SwiftUITests/GenericConstraintTests.swift
- Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUITests.swift
> Preview Providers now compile correctly

- Sources/SwiftCurrent/Models/Workflow.swift
- Tests/SwiftCurrentTests/WorkflowConsumerTests.swift
> Implements eraseToAnyWorkflow function on Workflow.

- .github/CODE_OF_CONDUCT.md
> Removes Richard Gist as point of contact from Code of Conduct and replaces with Matt Hartfield.

- .github/UPGRADE_PATH.md
- .github/abstract/Creating Workflows in UIKit.md
- .github/guides/Using Programmatic Views.md
- .github/guides/Using Storyboards.md
> The docs were using thenPresent but they should be using thenProceed

- Sources/SwiftCurrent_UIKit/Extensions/WorkflowUIKitAdditions.swift
There was an issue where calling `workflow.abandon` in the `onFinish` completion handler of a launched workflow could fail to be called because the `workflow` had already been deallocated. This caused ViewControllers to remain allocated. This issue did not occur when the workflow was abandoned within the workflow, but did reliably occur when trying to clean up when finishing.
By making this a strong reference, we can see in the memory graph that the ViewControllers are being reliably deallocated. I attached a video of me doing just this. Starting with the current code and showing all of the ViewControllers still in memory and then re-running with the strong reference showing all of the ViewControllers no longer in memory.
[video showing memory graph …
> Fixes an issue where holding self weakly is causing a memory leak when calling workflow.abandon

- Package.swift
- Sources/SwiftCurrent_CLI/Parser/File.swift
> Upping version of SwiftSyntax in the CLI to lastest.

- .github/workflows/CI.yml
- .github/workflows/PR_CI.yml
Looks like codecov's GitHub action has a new uploader and has sunset the v1 uploader. I bumped the version a bit higher to 3.0 due to some bug fixes added in between versions 2 and 3.
https://github.com/codecov/codecov-action/releases/tag/v2.0.0
> "On February 1, 2022, the v1 [uploader](https://github.com/codecov/uploader) will be full sunset and no longer function. This is due
to the deprecation of the underlying bash uploader. This version uses the new uploader."
> Updates codecov action version in pipeline.

- Sources/SwiftCurrent_Testing/CustomAssertions.swift
> Add variation of XCTAssertWorkflowLaunched for use with AnyWorkflow

- .github/SwiftCurrentLint/SwiftCurrentLint.xcodeproj/project.pbxproj
- .github/fastlane/Fastfile
- .github/fastlane/README.md
- .github/workflows/CI.yml
- .github/workflows/PR_CI.yml
- ExampleApps/SwiftUIExample/SwiftUIExampleTests/UIKitInteropTests.swift
- Sources/SwiftCurrent_SwiftUI/Protocols/_WorkflowItemProtocol.swift
- Sources/SwiftCurrent_SwiftUI/ResultBuilders/WorkflowBuilder.swift
- Sources/SwiftCurrent_SwiftUI/TypeErased/AnyWorkflowItem.swift
- Sources/SwiftCurrent_SwiftUI/Views/EitherWorkflowItem.swift
- Sources/SwiftCurrent_SwiftUI/Views/OptionalWorkflowItem.swift
- Sources/SwiftCurrent_SwiftUI/Views/WorkflowGroup.swift
- Sources/SwiftCurrent_SwiftUI/Views/WorkflowItem.swift
- Sources/SwiftCurrent_SwiftUI/Views/WorkflowItemWrapper.swift
- Tests/SwiftCurrent_SwiftUITests/GenericConstraintTests.swift
- Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUITests.swift
- Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUI_WorkflowBuilderArityTests.swift
- Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUI_WorkflowBuilderTests.swift
> Fixes an issue where skipping views with a NavigationStack or Modal presentation style didn't work correctly with SwiftUI

- Sources/SwiftCurrent_SwiftUI/Views/WorkflowLauncher.swift
- Sources/SwiftCurrent_SwiftUI/Views/WorkflowView.swift
- Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUITests.swift
> Add the ability to abandon workflow when a publisher emits a value

- Sources/SwiftCurrent_SwiftUI/Views/ViewControllerWrapper.swift
> [interop-abandon] - support workflow abandon with interop and navcontroller

- .github/UPGRADE_PATH.md
- .github/guides/Installation.md
- README.md
No linked issue, but I noticed these things in the documentation.
> Improving documentation
